spring.application.name=Microservicio-Usuarios

server.port=8083

spring.datasource.url=jdbc:oracle:thin:@donatonbd_high?TNS_ADMIN=C:/Users/ps.reyes/Desktop/Wallet_donatonBD
spring.datasource.username=ADMIN

spring.datasource.password=Donatonmicroservicios2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
